import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import city from "../assets/kuala-lumpur.jpg";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [isImageOpen, setIsImageOpen] = useState(false);
  const [isCardOpen, setIsCardOpen] = useState(true);

  const handleClick = () => {
    console.log("click");
    setIsImageOpen(true);
    setIsCardOpen(false);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&family=Rubik&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="h-screen flex items-center justify-center bg-gray-900">
          {isCardOpen && (
            <card className="bg-white rounded-lg w-[500px] h-[600px] flex items-center justify-center flex-col">
              <h1 className="mb-10">
                <span>Shared</span> by you
              </h1>
              <Image
                className="rounded-lg"
                alt="Picture of the author"
                width={380}
                height={270}
                src={city}
              ></Image>

              <h2 className="text-center font-Rubik text-4xl font-semibold mb-5 mt-5">
                Lost in Tokyo
              </h2>
              <p className="text-center font-Poppins max-w-[370px] mb-10">
                Tingling of the spine Apollonius of Perga cosmos Drake Equation
                concept of the number one brain is the seed of intelligence.
              </p>
              <button className="text-center" onClick={handleClick}>
                Expand
              </button>
            </card>
          )}

          {isImageOpen && (
            <card className="bg-white rounded-lg w-[500px] h-[600px] flex items-center justify-evenly flex-col relative">
              <Image
                className="flex z-10 rounded-lg"
                alt="Picture of the author"
                src={city}
                layout="fill"
              ></Image>
              <h1 className="z-40 text-white text-lg">hej</h1>
            </card>
          )}
        </div>
      </main>
    </>
  );
}
